### ISSUE TITLE
Cursor does not change to pointer on hover

### ISSUE THREAD

**Issue by DeveloperWil** [appleple/modal-video#37]
When hovering over an active modal-video button the cursor doesn't change to a pointer

**Comment by uidev1116** [comment]
@DeveloperWil 

Hi. Sorry for the late reply.

Please apply css yourself. 

``` css
.js-modal-btn {
  cursor: pointer;
}
```
